language: java

matrix:
  include:
  - os: osx
    before_install:
    - brew install python3
  - os: linux
    before_install:
    - sudo add-apt-repository ppa:deadsnakes/ppa -y
    - sudo apt-get update
    - sudo apt install software-properties-common
    - sudo apt-get install python3-pip
    - pip3 install --upgrade pip
    - sudo apt-get install python3-setuptools
    - sudo apt-get install python3.6

install:
   - pip3 install -r requirements.txt
   - pip3 install pytest
   - pwd
   - pip3 install -e .
   - pip3 install codecov
   - pip3 install pytest-cov

script: 
   - travis_wait python3 -m pytest --cov=netZooPy tests

branches:
  only:
  - master
  - devel

after_success:
   - codecov
