language: python
python:
   - "3.6"
   - "3.7"

install:
   - apt install build-essential python-dev libxml2 libxml2-dev zlib1g-dev
   - pip3 install -r requirements.txt
   - pip3 install pytest
   - pwd
   - pip3 install -e .
   - pip3 install codecov
   - pip install pytest-cov

script: 
   - pytest --cov=netZooPy tests

branches:
  only:
  - master
  - devel

after_success:
   - codecov
