-language: java

matrix:
  include:
  - os: osx
    before_install:
    - brew install python3

install:
   - pip3 install -r requirements.txt
   - pip3 install pytest
   - pwd
   - pip3 install -e .
   - pip3 install codecov
   - pip3 install pytest-cov

script: 
   - travis_wait pytest --cov=netZooPy tests

branches:
  only:
  - master
  - devel

after_success:
   - codecov
