language: java

matrix:
  include:
  - os: osx
    install:
    - pip3 install -r requirements.txt
    - pip3 install pytest
    - pip3 install -e .
    - pip3 install codecov
    - pip3 install pytest-cov
    script: 
    - travis_wait pytest --cov=netZooPy tests
  - os: xenial
    before_install:
    - sudo add-apt-repository ppa:deadsnakes/ppa -y
    - sudo apt-get update
    - sudo apt install software-properties-common
    - sudo apt-get install python3-pip
    - pip3 install --upgrade pip
    - sudo apt-get install python3-setuptools
    - sudo apt-get install python3.6
    - pyenv install 3.6.1
    - pyenv global 3.6.1
    - pip3.6 install -r requirements.txt
    - pip3.6 install pytest
    - pip3.6 install -e .
    - pip3.6 install codecov
    - pip3.6 install pytest-cov
    script: 
    - travis_wait python3.6 -m pytest --cov=netZooPy tests
  - dist: bionic
    before_install:
    - sudo add-apt-repository ppa:deadsnakes/ppa -y
    - sudo apt-get update
    - sudo apt install software-properties-common
    - sudo apt-get install python3-pip
    - pip3 install --upgrade pip
    - sudo apt-get install python3-setuptools
    - sudo apt-get install python3.7
    - pyenv global 3.7
    - pip3.7 install -r requirements.txt
    - pip3.7 install pytest
    - pip3.7 install -e .
    - pip3.7 install codecov
    - pip3.7 install pytest-cov
    script: 
    - travis_wait python3.7 -m pytest --cov=netZooPy tests
  - dist: bionic
    before_install:
    - sudo add-apt-repository ppa:deadsnakes/ppa -y
    - sudo apt-get update
    - sudo apt install software-properties-common
    - sudo apt-get install python3-pip
    - pip3 install --upgrade pip
    - sudo apt-get install python3-setuptools
    - sudo apt-get install python3.8
    - pyenv global 3.8
    - pip3.8 install -r requirements.txt
    - pip3.8 install pytest
    - pip3.8 install -e .
    - pip3.8 install codecov
    - pip3.8 install pytest-cov
    script: 
    - travis_wait python3.8 -m pytest --cov=netZooPy tests

branches:
  only:
  - master
  - devel

after_success:
   - codecov

